stof_doctrine_extensions:
    default_locale: fr # Default fallback language (French)
    class:
        translatable: App\Doctrine\AttributeTranslatableListener
    orm:
        default:
            timestampable: true
            sluggable: true
            softdeleteable: true

