<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419174740 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bookings CHANGE totalPrixBk totalPrixBk DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE decisions CHANGE StatutD StatutD ENUM(\'pending\',\'active\',\'refused\') NOT NULL DEFAULT \'pending\'');
        $this->addSql('ALTER TABLE decisions ADD CONSTRAINT FK_638DAA1721F1620E FOREIGN KEY (idProj) REFERENCES projects (idProj) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE decisions ADD CONSTRAINT FK_638DAA17FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (idUser)');
        $this->addSql('DROP INDEX fk_decisions_user ON decisions');
        $this->addSql('CREATE INDEX IDX_638DAA17FE6E88D7 ON decisions (idUser)');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY `fk_events_gerant`');
        $this->addSql('ALTER TABLE events CHANGE descriptionEv descriptionEv LONGTEXT DEFAULT NULL');
        $this->addSql('DROP INDEX fk_events_gerant ON events');
        $this->addSql('CREATE INDEX IDX_5387574AB2C5F4EA ON events (idGerant)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT `fk_events_gerant` FOREIGN KEY (idGerant) REFERENCES user (idUser) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE investments DROP FOREIGN KEY `fk_investments_project`');
        $this->addSql('ALTER TABLE investments DROP FOREIGN KEY `fk_investments_user`');
        $this->addSql('ALTER TABLE investments DROP FOREIGN KEY `fk_investments_project`');
        $this->addSql('ALTER TABLE investments DROP FOREIGN KEY `fk_investments_user`');
        $this->addSql('ALTER TABLE investments CHANGE bud_minInv bud_minInv DOUBLE PRECISION NOT NULL, CHANGE bud_maxInv bud_maxInv DOUBLE PRECISION NOT NULL, CHANGE CurrencyInv CurrencyInv VARCHAR(255) NOT NULL, CHANGE idProj idProj INT DEFAULT NULL, CHANGE idUser idUser INT DEFAULT NULL');
        $this->addSql('ALTER TABLE investments ADD CONSTRAINT FK_74FD72E021F1620E FOREIGN KEY (idProj) REFERENCES projects (idProj)');
        $this->addSql('ALTER TABLE investments ADD CONSTRAINT FK_74FD72E0FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (idUser)');
        $this->addSql('DROP INDEX fk_investments_project ON investments');
        $this->addSql('CREATE INDEX IDX_74FD72E021F1620E ON investments (idProj)');
        $this->addSql('DROP INDEX fk_investments_user ON investments');
        $this->addSql('CREATE INDEX IDX_74FD72E0FE6E88D7 ON investments (idUser)');
        $this->addSql('ALTER TABLE investments ADD CONSTRAINT `fk_investments_project` FOREIGN KEY (idProj) REFERENCES projects (idProj) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE investments ADD CONSTRAINT `fk_investments_user` FOREIGN KEY (idUser) REFERENCES user (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD id INT AUTO_INCREMENT NOT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL, CHANGE target_role target_role VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE objectives DROP FOREIGN KEY `fk_objectives_strategy`');
        $this->addSql('ALTER TABLE objectives DROP FOREIGN KEY `fk_objectives_strategy`');
        $this->addSql('ALTER TABLE objectives CHANGE priorityOb priorityOb INT DEFAULT NULL, CHANGE ids ids INT DEFAULT NULL, CHANGE nomObj nomObj VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE objectives ADD CONSTRAINT FK_6CB0696C70DAA798 FOREIGN KEY (ids) REFERENCES strategies (idStrategie)');
        $this->addSql('DROP INDEX fk_objectives_strategy ON objectives');
        $this->addSql('CREATE INDEX IDX_6CB0696C70DAA798 ON objectives (ids)');
        $this->addSql('ALTER TABLE objectives ADD CONSTRAINT `fk_objectives_strategy` FOREIGN KEY (ids) REFERENCES strategies (idStrategie) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_expires ON otp_code');
        $this->addSql('DROP INDEX idx_email_purpose ON otp_code');
        $this->addSql('ALTER TABLE otp_code CHANGE purpose purpose VARCHAR(255) NOT NULL, CHANGE code_hash code_hash VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_password_reset_user ON password_reset');
        $this->addSql('ALTER TABLE password_reset CHANGE created_at created_at DATETIME NOT NULL, CHANGE attempts attempts INT NOT NULL');
        $this->addSql('ALTER TABLE projects CHANGE budgetProj budgetProj DOUBLE PRECISION DEFAULT 0 NOT NULL, CHANGE stateProj stateProj ENUM(\'PENDING\',\'ACCEPTED\',\'REFUSED\',\'ARCHIVED\') NOT NULL DEFAULT \'PENDING\', CHANGE avancementProj avancementProj DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4A455ACCF FOREIGN KEY (idClient) REFERENCES user (idUser) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_5C93B3A4A455ACCF ON projects (idClient)');
        $this->addSql('ALTER TABLE project_resources ADD CONSTRAINT FK_FE5AAE7921F1620E FOREIGN KEY (idProj) REFERENCES projects (idProj) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_resources ADD CONSTRAINT FK_FE5AAE7969351B39 FOREIGN KEY (idRs) REFERENCES resources (idRs) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_FE5AAE7969351B39 ON project_resources (idRs)');
        $this->addSql('DROP INDEX idx_rmd_buyer ON resource_market_delivery');
        $this->addSql('DROP INDEX idx_rmd_status ON resource_market_delivery');
        $this->addSql('DROP INDEX idx_rmd_order ON resource_market_delivery');
        $this->addSql('ALTER TABLE resource_market_delivery CHANGE recipientName recipientName VARCHAR(255) NOT NULL, CHANGE city city VARCHAR(255) NOT NULL, CHANGE addressLine addressLine VARCHAR(255) NOT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE phone2 phone2 VARCHAR(255) DEFAULT NULL, CHANGE resourceName resourceName VARCHAR(255) DEFAULT NULL, CHANGE quantity quantity INT NOT NULL, CHANGE totalPrice totalPrice DOUBLE PRECISION NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE provider provider VARCHAR(255) NOT NULL, CHANGE trackingCode trackingCode VARCHAR(255) DEFAULT NULL, CHANGE labelUrl labelUrl VARCHAR(255) DEFAULT NULL, CHANGE providerMessage providerMessage VARCHAR(255) DEFAULT NULL, CHANGE createdAt createdAt DATETIME NOT NULL, CHANGE updatedAt updatedAt DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_rml_rs ON resource_market_listing');
        $this->addSql('DROP INDEX idx_rml_status ON resource_market_listing');
        $this->addSql('DROP INDEX idx_rml_seller_user ON resource_market_listing');
        $this->addSql('ALTER TABLE resource_market_listing CHANGE unitPrice unitPrice DOUBLE PRECISION NOT NULL, CHANGE note note VARCHAR(255) DEFAULT NULL, CHANGE imageUrl imageUrl VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE createdAt createdAt DATETIME NOT NULL, CHANGE updatedAt updatedAt DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_market_order_listing ON resource_market_order');
        $this->addSql('DROP INDEX idx_market_order_buyer ON resource_market_order');
        $this->addSql('DROP INDEX idx_market_order_seller ON resource_market_order');
        $this->addSql('ALTER TABLE resource_market_order CHANGE unitPrice unitPrice DOUBLE PRECISION NOT NULL, CHANGE totalPrice totalPrice DOUBLE PRECISION NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE createdAt createdAt DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_rmr_listing ON resource_market_review');
        $this->addSql('ALTER TABLE resource_market_review CHANGE comment comment VARCHAR(255) DEFAULT NULL, CHANGE createdAt createdAt DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_rwa_updated ON resource_wallet_account');
        $this->addSql('ALTER TABLE resource_wallet_account CHANGE idUser idUser INT AUTO_INCREMENT NOT NULL, CHANGE balanceCoins balanceCoins DOUBLE PRECISION NOT NULL, CHANGE updatedAt updatedAt DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_rwt_status ON resource_wallet_topup');
        $this->addSql('DROP INDEX idx_rwt_user ON resource_wallet_topup');
        $this->addSql('ALTER TABLE resource_wallet_topup CHANGE provider provider VARCHAR(255) NOT NULL, CHANGE amountMoney amountMoney DOUBLE PRECISION NOT NULL, CHANGE coinAmount coinAmount DOUBLE PRECISION NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE externalRef externalRef VARCHAR(255) DEFAULT NULL, CHANGE paymentUrl paymentUrl VARCHAR(255) DEFAULT NULL, CHANGE createdAt createdAt DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_rwx_user ON resource_wallet_txn');
        $this->addSql('DROP INDEX idx_rwx_type ON resource_wallet_txn');
        $this->addSql('ALTER TABLE resource_wallet_txn CHANGE txnType txnType VARCHAR(255) NOT NULL, CHANGE amountCoins amountCoins DOUBLE PRECISION NOT NULL, CHANGE balanceAfter balanceAfter DOUBLE PRECISION NOT NULL, CHANGE ref ref VARCHAR(255) DEFAULT NULL, CHANGE createdAt createdAt DATETIME NOT NULL');
        $this->addSql('ALTER TABLE resources DROP FOREIGN KEY `fk_resources_catalogue`');
        $this->addSql('ALTER TABLE resources DROP FOREIGN KEY `fk_resources_catalogue`');
        $this->addSql('ALTER TABLE resources CHANGE availabilityStatusRs availabilityStatusRs VARCHAR(255) NOT NULL, CHANGE nomRs nomRs VARCHAR(255) NOT NULL, CHANGE QuantiteRs QuantiteRs INT NOT NULL, CHANGE prixRs prixRs DOUBLE PRECISION NOT NULL, CHANGE idFr idFr INT DEFAULT NULL, CHANGE imageUrlRs imageUrlRs VARCHAR(255) DEFAULT NULL, CHANGE thumbnailUrlRs thumbnailUrlRs VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE resources ADD CONSTRAINT FK_EF66EBAE309CFCFA FOREIGN KEY (idFr) REFERENCES cataloguefournisseur (idFr)');
        $this->addSql('DROP INDEX fk_resources_catalogue ON resources');
        $this->addSql('CREATE INDEX IDX_EF66EBAE309CFCFA ON resources (idFr)');
        $this->addSql('ALTER TABLE resources ADD CONSTRAINT `fk_resources_catalogue` FOREIGN KEY (idFr) REFERENCES cataloguefournisseur (idFr) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE strategies DROP FOREIGN KEY `fk_strategies_project`');
        $this->addSql('ALTER TABLE strategies DROP FOREIGN KEY `fk_strategies_user`');
        $this->addSql('ALTER TABLE strategies DROP FOREIGN KEY `fk_strategies_project`');
        $this->addSql('ALTER TABLE strategies DROP FOREIGN KEY `fk_strategies_user`');
        $this->addSql('ALTER TABLE strategies DROP versions, CHANGE statusStrategie statusStrategie VARCHAR(255) NOT NULL, CHANGE CreatedAtS CreatedAtS DATETIME NOT NULL, CHANGE nomStrategie nomStrategie VARCHAR(255) NOT NULL, CHANGE justification justification VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE strategies ADD CONSTRAINT FK_611F221321F1620E FOREIGN KEY (idProj) REFERENCES projects (idProj)');
        $this->addSql('ALTER TABLE strategies ADD CONSTRAINT FK_611F2213FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (idUser)');
        $this->addSql('DROP INDEX fk_strategies_project ON strategies');
        $this->addSql('CREATE INDEX IDX_611F221321F1620E ON strategies (idProj)');
        $this->addSql('DROP INDEX fk_strategies_user ON strategies');
        $this->addSql('CREATE INDEX IDX_611F2213FE6E88D7 ON strategies (idUser)');
        $this->addSql('ALTER TABLE strategies ADD CONSTRAINT `fk_strategies_project` FOREIGN KEY (idProj) REFERENCES projects (idProj) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE strategies ADD CONSTRAINT `fk_strategies_user` FOREIGN KEY (idUser) REFERENCES user (idUser) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE swot_item DROP FOREIGN KEY `FK_SWOT_STRATEGIE`');
        $this->addSql('ALTER TABLE swot_item DROP FOREIGN KEY `FK_SWOT_STRATEGIE`');
        $this->addSql('ALTER TABLE swot_item CHANGE description description LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE swot_item ADD CONSTRAINT FK_E0E3A2F43AE1B9BD FOREIGN KEY (strategie_id) REFERENCES strategies (idStrategie)');
        $this->addSql('DROP INDEX idx_swot_strategie ON swot_item');
        $this->addSql('CREATE INDEX IDX_E0E3A2F43AE1B9BD ON swot_item (strategie_id)');
        $this->addSql('ALTER TABLE swot_item ADD CONSTRAINT `FK_SWOT_STRATEGIE` FOREIGN KEY (strategie_id) REFERENCES strategies (idStrategie) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY `fk_task_project`');
        $this->addSql('DROP INDEX idx_task_status ON task');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY `fk_task_project`');
        $this->addSql('ALTER TABLE task CHANGE project_id project_id INT DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE weight weight INT NOT NULL, CHANGE duration_days duration_days INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25166D1F9C FOREIGN KEY (project_id) REFERENCES projects (idProj)');
        $this->addSql('DROP INDEX idx_task_project ON task');
        $this->addSql('CREATE INDEX IDX_527EDB25166D1F9C ON task (project_id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT `fk_task_project` FOREIGN KEY (project_id) REFERENCES projects (idProj) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_transaction_investment`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_transaction_investment`');
        $this->addSql('ALTER TABLE transaction CHANGE DateTransac DateTransac DATE NOT NULL, CHANGE MontantTransac MontantTransac DOUBLE PRECISION NOT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE idInv idInv INT DEFAULT NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1DB17A61A FOREIGN KEY (idInv) REFERENCES investments (idInv)');
        $this->addSql('DROP INDEX fk_transaction_investment ON transaction');
        $this->addSql('CREATE INDEX IDX_723705D1DB17A61A ON transaction (idInv)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_transaction_investment` FOREIGN KEY (idInv) REFERENCES investments (idInv) ON DELETE CASCADE');
        $this->addSql('DROP INDEX cin ON user');
        $this->addSql('DROP INDEX NumTelUser ON user');
        $this->addSql('DROP INDEX EmailUser ON user');
        $this->addSql('ALTER TABLE user CHANGE cin cin VARCHAR(255) DEFAULT NULL, CHANGE EmailUser EmailUser VARCHAR(255) NOT NULL, CHANGE nomUser nomUser VARCHAR(255) NOT NULL, CHANGE PrenomUser PrenomUser VARCHAR(255) NOT NULL, CHANGE NumTelUser NumTelUser VARCHAR(255) DEFAULT NULL, CHANGE roleUser roleUser VARCHAR(255) NOT NULL, CHANGE expertiseAreaUser expertiseAreaUser VARCHAR(255) DEFAULT NULL, CHANGE createdAt createdAt DATETIME NOT NULL, CHANGE updatedAt updatedAt DATETIME NOT NULL, CHANGE totp_secret totp_secret VARCHAR(255) DEFAULT NULL, CHANGE totp_enabled totp_enabled TINYINT NOT NULL, CHANGE failed_login_count failed_login_count INT NOT NULL');
        $this->addSql('ALTER TABLE userlog DROP FOREIGN KEY `fk_userLog_user`');
        $this->addSql('ALTER TABLE userlog DROP FOREIGN KEY `fk_userLog_user`');
        $this->addSql('ALTER TABLE userlog CHANGE user_id user_id INT DEFAULT NULL, CHANGE dateLog dateLog DATETIME NOT NULL, CHANGE ip_address ip_address VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE userlog ADD CONSTRAINT FK_4E107E60A76ED395 FOREIGN KEY (user_id) REFERENCES user (idUser)');
        $this->addSql('DROP INDEX fk_userlog_user ON userlog');
        $this->addSql('CREATE INDEX IDX_4E107E60A76ED395 ON userlog (user_id)');
        $this->addSql('ALTER TABLE userlog ADD CONSTRAINT `fk_userLog_user` FOREIGN KEY (user_id) REFERENCES user (idUser) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bookings CHANGE totalPrixBk totalPrixBk DOUBLE PRECISION DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE decisions DROP FOREIGN KEY FK_638DAA1721F1620E');
        $this->addSql('ALTER TABLE decisions DROP FOREIGN KEY FK_638DAA17FE6E88D7');
        $this->addSql('ALTER TABLE decisions DROP FOREIGN KEY FK_638DAA17FE6E88D7');
        $this->addSql('ALTER TABLE decisions CHANGE StatutD StatutD ENUM(\'pending\', \'active\', \'refused\') DEFAULT \'pending\' NOT NULL');
        $this->addSql('DROP INDEX idx_638daa17fe6e88d7 ON decisions');
        $this->addSql('CREATE INDEX fk_decisions_user ON decisions (idUser)');
        $this->addSql('ALTER TABLE decisions ADD CONSTRAINT FK_638DAA17FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (idUser)');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY FK_5387574AB2C5F4EA');
        $this->addSql('ALTER TABLE events CHANGE descriptionEv descriptionEv TEXT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_5387574ab2c5f4ea ON events');
        $this->addSql('CREATE INDEX fk_events_gerant ON events (idGerant)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574AB2C5F4EA FOREIGN KEY (idGerant) REFERENCES user (idUser) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE investments DROP FOREIGN KEY FK_74FD72E021F1620E');
        $this->addSql('ALTER TABLE investments DROP FOREIGN KEY FK_74FD72E0FE6E88D7');
        $this->addSql('ALTER TABLE investments DROP FOREIGN KEY FK_74FD72E021F1620E');
        $this->addSql('ALTER TABLE investments DROP FOREIGN KEY FK_74FD72E0FE6E88D7');
        $this->addSql('ALTER TABLE investments CHANGE bud_minInv bud_minInv DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE bud_maxInv bud_maxInv DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE CurrencyInv CurrencyInv VARCHAR(10) DEFAULT \'TND\' NOT NULL, CHANGE idProj idProj INT NOT NULL, CHANGE idUser idUser INT NOT NULL');
        $this->addSql('ALTER TABLE investments ADD CONSTRAINT `fk_investments_project` FOREIGN KEY (idProj) REFERENCES projects (idProj) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE investments ADD CONSTRAINT `fk_investments_user` FOREIGN KEY (idUser) REFERENCES user (idUser) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_74fd72e021f1620e ON investments');
        $this->addSql('CREATE INDEX fk_investments_project ON investments (idProj)');
        $this->addSql('DROP INDEX idx_74fd72e0fe6e88d7 ON investments');
        $this->addSql('CREATE INDEX fk_investments_user ON investments (idUser)');
        $this->addSql('ALTER TABLE investments ADD CONSTRAINT FK_74FD72E021F1620E FOREIGN KEY (idProj) REFERENCES projects (idProj)');
        $this->addSql('ALTER TABLE investments ADD CONSTRAINT FK_74FD72E0FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (idUser)');
        $this->addSql('ALTER TABLE notification MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE notification DROP id, CHANGE title title VARCHAR(100) NOT NULL, CHANGE description description VARCHAR(400) NOT NULL, CHANGE target_role target_role VARCHAR(20) DEFAULT NULL, DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE objectives DROP FOREIGN KEY FK_6CB0696C70DAA798');
        $this->addSql('ALTER TABLE objectives DROP FOREIGN KEY FK_6CB0696C70DAA798');
        $this->addSql('ALTER TABLE objectives CHANGE priorityOb priorityOb INT DEFAULT 0, CHANGE nomObj nomObj VARCHAR(200) DEFAULT NULL, CHANGE ids ids INT NOT NULL');
        $this->addSql('ALTER TABLE objectives ADD CONSTRAINT `fk_objectives_strategy` FOREIGN KEY (ids) REFERENCES strategies (idStrategie) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_6cb0696c70daa798 ON objectives');
        $this->addSql('CREATE INDEX fk_objectives_strategy ON objectives (ids)');
        $this->addSql('ALTER TABLE objectives ADD CONSTRAINT FK_6CB0696C70DAA798 FOREIGN KEY (ids) REFERENCES strategies (idStrategie)');
        $this->addSql('ALTER TABLE otp_code CHANGE purpose purpose VARCHAR(20) NOT NULL, CHANGE code_hash code_hash VARCHAR(64) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_expires ON otp_code (expires_at)');
        $this->addSql('CREATE INDEX idx_email_purpose ON otp_code (email, purpose)');
        $this->addSql('ALTER TABLE password_reset CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE attempts attempts INT DEFAULT 0 NOT NULL');
        $this->addSql('CREATE INDEX idx_password_reset_user ON password_reset (user_id)');
        $this->addSql('ALTER TABLE projects DROP FOREIGN KEY FK_5C93B3A4A455ACCF');
        $this->addSql('DROP INDEX IDX_5C93B3A4A455ACCF ON projects');
        $this->addSql('ALTER TABLE projects CHANGE budgetProj budgetProj DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE stateProj stateProj ENUM(\'PENDING\', \'ACCEPTED\', \'REFUSED\', \'ARCHIVED\') DEFAULT \'PENDING\' NOT NULL, CHANGE avancementProj avancementProj DOUBLE PRECISION DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE project_resources DROP FOREIGN KEY FK_FE5AAE7921F1620E');
        $this->addSql('ALTER TABLE project_resources DROP FOREIGN KEY FK_FE5AAE7969351B39');
        $this->addSql('DROP INDEX IDX_FE5AAE7969351B39 ON project_resources');
        $this->addSql('ALTER TABLE resources DROP FOREIGN KEY FK_EF66EBAE309CFCFA');
        $this->addSql('ALTER TABLE resources DROP FOREIGN KEY FK_EF66EBAE309CFCFA');
        $this->addSql('ALTER TABLE resources CHANGE availabilityStatusRs availabilityStatusRs ENUM(\'AVAILABLE\', \'RESERVED\', \'UNAVAILABLE\') DEFAULT \'AVAILABLE\' NOT NULL, CHANGE nomRs nomRs VARCHAR(160) NOT NULL, CHANGE QuantiteRs QuantiteRs INT DEFAULT 0 NOT NULL, CHANGE prixRs prixRs DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE imageUrlRs imageUrlRs VARCHAR(700) DEFAULT NULL, CHANGE thumbnailUrlRs thumbnailUrlRs VARCHAR(512) DEFAULT NULL, CHANGE idFr idFr INT NOT NULL');
        $this->addSql('ALTER TABLE resources ADD CONSTRAINT `fk_resources_catalogue` FOREIGN KEY (idFr) REFERENCES cataloguefournisseur (idFr) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_ef66ebae309cfcfa ON resources');
        $this->addSql('CREATE INDEX fk_resources_catalogue ON resources (idFr)');
        $this->addSql('ALTER TABLE resources ADD CONSTRAINT FK_EF66EBAE309CFCFA FOREIGN KEY (idFr) REFERENCES cataloguefournisseur (idFr)');
        $this->addSql('ALTER TABLE resource_market_delivery CHANGE recipientName recipientName VARCHAR(160) NOT NULL, CHANGE city city VARCHAR(120) NOT NULL, CHANGE addressLine addressLine VARCHAR(260) NOT NULL, CHANGE phone phone VARCHAR(40) DEFAULT NULL, CHANGE phone2 phone2 VARCHAR(40) DEFAULT NULL, CHANGE resourceName resourceName VARCHAR(200) DEFAULT NULL, CHANGE quantity quantity INT DEFAULT 1 NOT NULL, CHANGE totalPrice totalPrice NUMERIC(12, 4) DEFAULT \'0.0000\' NOT NULL, CHANGE status status VARCHAR(30) DEFAULT \'EN_PREPARATION\' NOT NULL, CHANGE provider provider VARCHAR(40) DEFAULT \'FIABILO\' NOT NULL, CHANGE trackingCode trackingCode VARCHAR(140) DEFAULT NULL, CHANGE labelUrl labelUrl VARCHAR(700) DEFAULT NULL, CHANGE providerMessage providerMessage VARCHAR(400) DEFAULT NULL, CHANGE createdAt createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updatedAt updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_rmd_buyer ON resource_market_delivery (buyerUserId)');
        $this->addSql('CREATE INDEX idx_rmd_status ON resource_market_delivery (status)');
        $this->addSql('CREATE INDEX idx_rmd_order ON resource_market_delivery (idOrder)');
        $this->addSql('ALTER TABLE resource_market_listing CHANGE unitPrice unitPrice NUMERIC(12, 4) NOT NULL, CHANGE note note VARCHAR(300) DEFAULT NULL, CHANGE imageUrl imageUrl VARCHAR(600) DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'LISTED\' NOT NULL, CHANGE createdAt createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updatedAt updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_rml_rs ON resource_market_listing (idRs)');
        $this->addSql('CREATE INDEX idx_rml_status ON resource_market_listing (status)');
        $this->addSql('CREATE INDEX idx_rml_seller_user ON resource_market_listing (sellerUserId)');
        $this->addSql('ALTER TABLE resource_market_order CHANGE unitPrice unitPrice NUMERIC(12, 4) NOT NULL, CHANGE totalPrice totalPrice NUMERIC(12, 4) NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'COMPLETED\' NOT NULL, CHANGE createdAt createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_market_order_listing ON resource_market_order (idListing)');
        $this->addSql('CREATE INDEX idx_market_order_buyer ON resource_market_order (buyerUserId)');
        $this->addSql('CREATE INDEX idx_market_order_seller ON resource_market_order (sellerUserId)');
        $this->addSql('ALTER TABLE resource_market_review CHANGE comment comment VARCHAR(400) DEFAULT NULL, CHANGE createdAt createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_rmr_listing ON resource_market_review (idListing)');
        $this->addSql('ALTER TABLE resource_wallet_account CHANGE idUser idUser INT NOT NULL, CHANGE balanceCoins balanceCoins NUMERIC(14, 4) DEFAULT \'0.0000\' NOT NULL, CHANGE updatedAt updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_rwa_updated ON resource_wallet_account (updatedAt)');
        $this->addSql('ALTER TABLE resource_wallet_topup CHANGE provider provider VARCHAR(20) NOT NULL, CHANGE amountMoney amountMoney NUMERIC(14, 4) NOT NULL, CHANGE coinAmount coinAmount NUMERIC(14, 4) NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'PENDING\' NOT NULL, CHANGE externalRef externalRef VARCHAR(140) DEFAULT NULL, CHANGE paymentUrl paymentUrl VARCHAR(700) DEFAULT NULL, CHANGE createdAt createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_rwt_status ON resource_wallet_topup (status)');
        $this->addSql('CREATE INDEX idx_rwt_user ON resource_wallet_topup (idUser)');
        $this->addSql('ALTER TABLE resource_wallet_txn CHANGE txnType txnType VARCHAR(30) NOT NULL, CHANGE amountCoins amountCoins NUMERIC(14, 4) NOT NULL, CHANGE balanceAfter balanceAfter NUMERIC(14, 4) NOT NULL, CHANGE ref ref VARCHAR(180) DEFAULT NULL, CHANGE createdAt createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_rwx_user ON resource_wallet_txn (idUser)');
        $this->addSql('CREATE INDEX idx_rwx_type ON resource_wallet_txn (txnType)');
        $this->addSql('ALTER TABLE strategies DROP FOREIGN KEY FK_611F221321F1620E');
        $this->addSql('ALTER TABLE strategies DROP FOREIGN KEY FK_611F2213FE6E88D7');
        $this->addSql('ALTER TABLE strategies DROP FOREIGN KEY FK_611F221321F1620E');
        $this->addSql('ALTER TABLE strategies DROP FOREIGN KEY FK_611F2213FE6E88D7');
        $this->addSql('ALTER TABLE strategies ADD versions INT DEFAULT 1 NOT NULL, CHANGE statusStrategie statusStrategie ENUM(\'En_cours\', \'Acceptée\', \'Refusée\', \'En_attente\', \'Non_affectée\') DEFAULT \'En_attente\' NOT NULL, CHANGE CreatedAtS CreatedAtS DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE nomStrategie nomStrategie VARCHAR(50) NOT NULL, CHANGE justification justification VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE strategies ADD CONSTRAINT `fk_strategies_project` FOREIGN KEY (idProj) REFERENCES projects (idProj) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE strategies ADD CONSTRAINT `fk_strategies_user` FOREIGN KEY (idUser) REFERENCES user (idUser) ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_611f221321f1620e ON strategies');
        $this->addSql('CREATE INDEX fk_strategies_project ON strategies (idProj)');
        $this->addSql('DROP INDEX idx_611f2213fe6e88d7 ON strategies');
        $this->addSql('CREATE INDEX fk_strategies_user ON strategies (idUser)');
        $this->addSql('ALTER TABLE strategies ADD CONSTRAINT FK_611F221321F1620E FOREIGN KEY (idProj) REFERENCES projects (idProj)');
        $this->addSql('ALTER TABLE strategies ADD CONSTRAINT FK_611F2213FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (idUser)');
        $this->addSql('ALTER TABLE swot_item DROP FOREIGN KEY FK_E0E3A2F43AE1B9BD');
        $this->addSql('ALTER TABLE swot_item DROP FOREIGN KEY FK_E0E3A2F43AE1B9BD');
        $this->addSql('ALTER TABLE swot_item CHANGE description description TEXT NOT NULL');
        $this->addSql('ALTER TABLE swot_item ADD CONSTRAINT `FK_SWOT_STRATEGIE` FOREIGN KEY (strategie_id) REFERENCES strategies (idStrategie) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_e0e3a2f43ae1b9bd ON swot_item');
        $this->addSql('CREATE INDEX IDX_SWOT_STRATEGIE ON swot_item (strategie_id)');
        $this->addSql('ALTER TABLE swot_item ADD CONSTRAINT FK_E0E3A2F43AE1B9BD FOREIGN KEY (strategie_id) REFERENCES strategies (idStrategie)');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25166D1F9C');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25166D1F9C');
        $this->addSql('ALTER TABLE task CHANGE status status ENUM(\'TODO\', \'IN_PROGRESS\', \'DONE\') DEFAULT \'TODO\' NOT NULL, CHANGE weight weight INT DEFAULT 1 NOT NULL, CHANGE duration_days duration_days INT DEFAULT 1 NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE project_id project_id INT NOT NULL');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT `fk_task_project` FOREIGN KEY (project_id) REFERENCES projects (idProj) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_task_status ON task (status)');
        $this->addSql('DROP INDEX idx_527edb25166d1f9c ON task');
        $this->addSql('CREATE INDEX idx_task_project ON task (project_id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25166D1F9C FOREIGN KEY (project_id) REFERENCES projects (idProj)');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1DB17A61A');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1DB17A61A');
        $this->addSql('ALTER TABLE transaction CHANGE DateTransac DateTransac DATE DEFAULT CURRENT_DATE NOT NULL, CHANGE MontantTransac MontantTransac DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE type type VARCHAR(60) DEFAULT NULL, CHANGE statut statut ENUM(\'PENDING\', \'SUCCESS\', \'FAILED\') DEFAULT \'PENDING\' NOT NULL, CHANGE idInv idInv INT NOT NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_transaction_investment` FOREIGN KEY (idInv) REFERENCES investments (idInv) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_723705d1db17a61a ON transaction');
        $this->addSql('CREATE INDEX fk_transaction_investment ON transaction (idInv)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1DB17A61A FOREIGN KEY (idInv) REFERENCES investments (idInv)');
        $this->addSql('ALTER TABLE user CHANGE cin cin VARCHAR(20) DEFAULT NULL, CHANGE EmailUser EmailUser VARCHAR(190) NOT NULL, CHANGE nomUser nomUser VARCHAR(100) NOT NULL, CHANGE PrenomUser PrenomUser VARCHAR(100) NOT NULL, CHANGE NumTelUser NumTelUser VARCHAR(30) DEFAULT NULL, CHANGE roleUser roleUser ENUM(\'client\', \'gerant\', \'admin\') DEFAULT \'client\' NOT NULL, CHANGE expertiseAreaUser expertiseAreaUser VARCHAR(150) DEFAULT NULL, CHANGE createdAt createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updatedAt updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE totp_secret totp_secret VARCHAR(64) DEFAULT NULL, CHANGE totp_enabled totp_enabled TINYINT DEFAULT 0 NOT NULL, CHANGE failed_login_count failed_login_count INT DEFAULT 0 NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX cin ON user (cin)');
        $this->addSql('CREATE UNIQUE INDEX NumTelUser ON user (NumTelUser)');
        $this->addSql('CREATE UNIQUE INDEX EmailUser ON user (EmailUser)');
        $this->addSql('ALTER TABLE userlog DROP FOREIGN KEY FK_4E107E60A76ED395');
        $this->addSql('ALTER TABLE userlog DROP FOREIGN KEY FK_4E107E60A76ED395');
        $this->addSql('ALTER TABLE userlog CHANGE dateLog dateLog DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE ip_address ip_address VARCHAR(45) DEFAULT NULL, CHANGE user_id user_id INT NOT NULL');
        $this->addSql('ALTER TABLE userlog ADD CONSTRAINT `fk_userLog_user` FOREIGN KEY (user_id) REFERENCES user (idUser) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_4e107e60a76ed395 ON userlog');
        $this->addSql('CREATE INDEX fk_userLog_user ON userlog (user_id)');
        $this->addSql('ALTER TABLE userlog ADD CONSTRAINT FK_4E107E60A76ED395 FOREIGN KEY (user_id) REFERENCES user (idUser)');
    }
}
